### ISSUE TITLE
Liquid crystal doesn't exist

### ISSUE THREAD

**Issue by Spontaneo** [McJty/DeepResonance#294]
Playing in the TNP 5  Deepr Resonance Version 3.0.4-beta

Smelter will not process resonant ore and the liquid crystal does not appear in JEI.

**Comment by McJty** [comment]
Can you give me more information? Exactly how are you doing it? Can you show me some screenshots?

**Comment by Calrizan** [comment]
I was able to verify that JEI does not display **Resonating Crystal Liquid** when searching for the liquid via the **@Deep Resonance**  tag, nor does the smelter produce the liquid in question despite consuming the ore. However, using the Liquid Injector will fill a tank with the aforementioned fluid.

We are running version 3.0.4-Beta included with All The Mods 7's most recent update.
![image](https://user-images.githubusercontent.com/5266831/169172987-133db968-5cc5-41c8-943b-1bb0cae614d8.png)

**Comment by McJty** [comment]
Can you tell me how you are trying to produce the liquid? I could produce it so I'm wondering if you are doing it correctly. Show me your setup

**Comment by McJty** [comment]
Here is a working setup:

![image](https://user-images.githubusercontent.com/8188472/169202266-78843a26-07f2-4f61-99ab-efa7339395e0.png)

Important! Lava tank below the smelter should only be filled between 40 and 60%. If you put in too much it will indeed destroy the liquid

**Comment by Firestar311** [comment]
I can confirm this does not work with the 1.2.0 version of the Direwolf 20 1.18.2 Pack. The tank has 5k mb of lava in the bottom and it doesn't put it in the tank. And I cannot see the fluid in JEI either as well.

![2022-05-21_18 15 05](https://user-images.githubusercontent.com/9711989/169671884-95ebed48-7445-44c4-b890-447e552fe4cc.png)

Also when I took this screenshot, it didnt even process the ore I had in the smelter

**Comment by Firestar311** [comment]
I did some testing, this seems to be a bug on multiplayer

**Comment by McJty** [comment]
Then I need to see server logs

**Comment by Calrizan** [comment]
I can't reproduce what problem we had, but it seems to have mysteriously resolved with a restart, and in the case of Singleplayer, it resolved when I paused and unpaused. Terrifically bizarre.

**Comment by cineruss** [comment]
A restart did resolve the issue of the process not starting. But in the tank above were no liquid, even not after 30 resonating ores even with varying the lava level. Can confirm JEI not showing the liquid and under /give i hadn't found the liquid too.

Modpack is DireWolf20 1.18.2 1.4.1

**Comment by ProsperCraft** [comment]
Alpha JEI has broken liquids, swap out your JEI with a release version.

**Comment by Toskin** [comment]
Same problem with version 3.0.6 with jei 9.7.0.195 on modpack Eternal Pillars, version 1.18.2. Smelter doesn't produce liquid crystal, and JEI doesn't show the liquid. I'm still able to add liquid through injector though. Error persists even with latest Deep Resonance, JEI, and Mcjtylib replacing older mod versions.

**Comment by McJty** [comment]
You are making sure the tank with lava below is only between 40 and 60 %
filled? If it's above 69% filled the liquid crystal will be destroyed


Op zo 3 jul. 2022 15:42 schreef Toskin ***@***.***>:

**Comment by Alainx277** [comment]
Same problem on Direwolf 20 1.20. Mod version 1.20-5.0.2

The smelter consumed the ore, but did not take any lava from the tank below, as well as not outputting any liquid into the above tank. A minute or two later the server also crashed, although I cannot confirm that this is due to the mod (can't get the crash logs right now, server hadn't ever crashed before).
After the server restart the smelter works as expected.

Edit: Same problem with purifier, except it just does nothing at all. I also found out that unloading the chunk the machine is in makes the next tick take a long time, up to 60 seconds (which triggers a watchdog).

**Comment by McJty** [comment]
How much lava was in the tank?

**Comment by Alainx277** [comment]
> How much lava was in the tank?

6000mb. After server restart it produced a 100% quality liquid.
